CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  login VARCHAR(255) UNIQUE NOT NULL,
  pass_hash VARCHAR(255) NOT NULL,
  application_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (application_id) REFERENCES application(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;